insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("아이패드Air3", "tablet", 70, "Apple", 300, "최신형 태블릿")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("MacBook Pro", "laptop", 300, "Apple", 320, "최신형 노트북 13인치형/16인치형")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("갤럭시 탭 S6", "tablet", 40, "삼성전자", 100, "신작, 삼성태블릿!")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("초코칩쿠키", "baking", 1, "비밀", 100, "다크초콜릿이 한봉지 들어간 초코칩쿠키!")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("슈퍼스타", "stuff", 10, "아디다스", 200, "아디다스 최고 인기의 운동화!!!")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("The Last of Us", "game", 6, "PS", 250, "2020년 6월 19일에 출시!")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("따뚜아쥬 꾸뛰르 타투 틴트", "cosmetic", 4, "YSL", 20, "올해에 재입고 된 인기의 타투 틴트")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("발사믹 식초", "food", 1, "올레이피쵸라니에리", 50, "이탈리아에서 건너 온 15년된 발사믹 식초")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("에어프라이어", "electronic", 12, "리큅", 200, "최신형 에어프라이어")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("드라이기", "electronic", 2, "다이슨", 100, "신형 드라이기")